# -*- coding: utf-8 -*-
"""Fake-News_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2S-YcUZqFOCtdOVk7MB4GC223nyyJof
"""

# Step 1: Install & Imports
!pip install -q transformers datasets scikit-learn pandas matplotlib seaborn torch

import pandas as pd
import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

# Create a dummy CSV file for demonstration purposes
dummy_data = {
    'title': [
        'Breaking: Scientists discover water on Mars',
        'Exclusive: Local resident spots Bigfoot in national park',
        'New study shows health benefits of daily chocolate consumption',
        'Government announces new policy on renewable energy',
        'Tabloid claims celebrity is an alien robot',
        'Expert analysis on global economic trends',
        'New research confirms benefits of meditation for stress',
        'Another politician involved in scandal uncovered',
        'Global warming effects becoming more evident every year',
        'Fake news article about celebrity cloning goes viral',
        'Major breakthrough in cancer research announced',
        'Conspiracy theory about moon landing debunked',
        'Study reveals dangers of excessive screen time',
        'Sensational headline about a new animal species discovered'
    ],
    'text': [
        'Recent findings from NASA rovers confirm the presence of liquid water.',
        'Eyewitness accounts describe a large, hairy bipedal creature.',
        'Researchers from a leading university published their findings today.',
        'The environment minister detailed the initiative in a press conference.',
        'Sources close to the star reveal shocking information.',
        'Economists weigh in on the potential impact of recent market shifts.',
        'Scientists confirm that daily meditation can significantly reduce stress levels.',
        'Reports suggest a prominent politician has been linked to a major financial impropriety.',
        'Climate models show an accelerating trend in global temperature rise.',
        'Unverified reports claim a famous actor has been replaced by a clone.',
        'A novel treatment showing high efficacy in late-stage trials was revealed.',
        'Experts provide overwhelming evidence disproving lunar landing conspiracy theories.',
        'Medical study highlights the negative health impacts of prolonged digital device use.',
        'A bizarre new creature was reportedly found in the Amazon rainforest.'
    ],
    'fake_or_factual': [
        'Factual News', 'Fake News', 'Factual News',
        'Factual News', 'Fake News', 'Factual News',
        'Factual News', 'Fake News', 'Factual News',
        'Fake News', 'Factual News', 'Fake News',
        'Factual News', 'Fake News'
    ]
}
dummy_df = pd.DataFrame(dummy_data)
dummy_df.to_csv('fake_news_data.csv', index=False)

# Step 2: Load Data
df = pd.read_csv('fake_news_data.csv')
df['label'] = df['fake_or_factual'].map({'Factual News': 0, 'Fake News': 1})
df['content'] = df['title'].astype(str) + " [SEP] " + df['text'].astype(str)

# Step 3: Split Data
X_train, X_temp, y_train, y_temp = train_test_split(df['content'].tolist(), df['label'].tolist(), test_size=0.3, stratify=df['label'], random_state=SEED)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=SEED)

# Step 4: Tokenization & Dataset
MODEL_NAME = "distilbert-base-uncased"
tokenizer = DistilBertTokenizerFast.from_pretrained(MODEL_NAME)

class NewsDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item
    def __len__(self):
        return len(self.labels)

train_enc = tokenizer(X_train, truncation=True, padding=True, max_length=256)
val_enc = tokenizer(X_val, truncation=True, padding=True, max_length=256)

train_dataset = NewsDataset(train_enc, y_train)
val_dataset = NewsDataset(val_enc, y_val)
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8)

# Step 5: Model Setup
model = DistilBertForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)
model.to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)

# Step 6: Training Loop
for epoch in range(3):
    model.train()
    for batch in train_loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)
        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1} complete.")

from sklearn.metrics import confusion_matrix

# Step 7: Final Evaluation
test_enc = tokenizer(X_test, truncation=True, padding=True, max_length=256)
test_dataset = NewsDataset(test_enc, y_test)
test_loader = DataLoader(test_dataset, batch_size=8)

model.eval()
all_preds = []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        outputs = model(input_ids, attention_mask=attention_mask)
        preds = torch.argmax(outputs.logits, dim=1)
        all_preds.extend(preds.cpu().numpy())

print("Test Accuracy:", accuracy_score(y_test, all_preds))
print("\nClassification Report:\n", classification_report(y_test, all_preds, target_names=['Factual News', 'Fake News']))

# Confusion Matrix Visualization
cm = confusion_matrix(y_test, all_preds)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Factual', 'Fake'], yticklabels=['Factual', 'Fake'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

def predict_news(text):
    # Prepare the input
    inputs = tokenizer(text, truncation=True, padding=True, max_length=256, return_tensors="pt").to(device)

    # Get prediction
    model.eval()
    with torch.no_grad():
        outputs = model(**inputs)
        prediction = torch.argmax(outputs.logits, dim=1).item()

    return "Fake News" if prediction == 1 else "Factual News"

# Test examples
headlines = [
    "Scientists discover water on a new exoplanet in the habitable zone.",
    "Breaking: Local man finds secret portal to another dimension in his basement.",
    "Government announces new tax reforms to take effect next fiscal year."
]

for text in headlines:
    result = predict_news(text)
    print(f"Headline: {text}\nResult: {result}\n{'-'*30}")

import torch
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification

# Re-initialize basic settings
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
MODEL_NAME = 'distilbert-base-uncased'

# Initialize tokenizer and model
tokenizer = DistilBertTokenizerFast.from_pretrained(MODEL_NAME)
model = DistilBertForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)
model.to(device)

print(f'Model and tokenizer re-initialized on {device}.')

import torch
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification

# Ensure model and tokenizer are defined in the current session
MODEL_NAME = 'distilbert-base-uncased'
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

tokenizer = DistilBertTokenizerFast.from_pretrained(MODEL_NAME)
model = DistilBertForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)
model.to(device)

# Save trained model and tokenizer
model.save_pretrained("./fake_news_model")
tokenizer.save_pretrained("./fake_news_model")

print("Model and tokenizer saved successfully to ./fake_news_model")

import os

print(os.listdir("./fake_news_model"))

from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification
)

saved_tokenizer = DistilBertTokenizerFast.from_pretrained(
    "./fake_news_model"
)

saved_model = DistilBertForSequenceClassification.from_pretrained(
    "./fake_news_model"
)

print("Saved model loaded successfully!")

import torch

def predict_news(title, text):

    input_text = title + " " + text

    inputs = saved_tokenizer(
        input_text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=512
    )

    with torch.no_grad():

        outputs = saved_model(**inputs)

    probabilities = torch.softmax(
        outputs.logits,
        dim=1
    )

    predicted_class = torch.argmax(
        probabilities,
        dim=1
    ).item()

    confidence = probabilities[0][predicted_class].item() * 100

    if predicted_class == 0:
    prediction = "Factual News"
else:
    prediction = "Fake News"

    return prediction, confidence

title = "Example news headline"

text = """
This is an example news article.
The article contains some information
that the model will classify.
"""

prediction, confidence = predict_news(
    title,
    text
)

print("Prediction:", prediction)
print("Confidence:", round(confidence, 2), "%")

def predict_news(title, text):

    input_text = title + " " + text

    # The .to(device) ensures tensors match the model's location (CPU or GPU)
    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=512
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    probabilities = torch.softmax(
        outputs.logits,
        dim=1
    )

    predicted_class = torch.argmax(
        probabilities,
        dim=1
    ).item()

    confidence = (
        probabilities[0][predicted_class].item() * 100
    )

    return predicted_class, confidence

# Ensure model is on the correct device before calling
model.to(device)

prediction, confidence = predict_news(
    "Example news headline",
    "This is an example news article."
)

print("Class:", prediction)
print("Confidence:", round(confidence, 2), "%")

!pip install flask flask-cors pyngrok

from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)


@app.route("/")
def home():

    return jsonify({
        "message": "Fake News Detection API is running"
    })


@app.route("/predict", methods=["POST"])
def predict():

    data = request.get_json()

    title = data.get("title", "")
    text = data.get("text", "")

    if not title and not text:

        return jsonify({
            "error": "Please enter news headline or article"
        }), 400


    predicted_class, confidence = predict_news(
        title,
        text
    )


    # IMPORTANT:
    # Change this only if your original label mapping
    # is different.

    if predicted_class == 0:
        prediction = "Fake News"
    else:
        prediction = "Factual News"


    return jsonify({

        "prediction": prediction,

        "confidence": round(confidence, 2)

    })

"""### Step 10: Set up the Public URL
Paste your ngrok token below to create a public link for your API.
"""

import os

print("Checking model folder...")
print(os.path.exists("/content/fake_news_model"))

print("\nFiles inside model folder:")
print(os.listdir("/content/fake_news_model"))

from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification
)
import torch

MODEL_PATH = "/content/fake_news_model"

tokenizer = DistilBertTokenizerFast.from_pretrained(
    MODEL_PATH
)

model = DistilBertForSequenceClassification.from_pretrained(
    MODEL_PATH
)

model.eval()

print("✅ Tokenizer loaded successfully")
print("✅ Model loaded successfully")
print("Number of labels:", model.config.num_labels)

def predict_news(title, text):

    input_text = title + " " + text

    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=512
    )

    with torch.no_grad():
        outputs = model(**inputs)

    probabilities = torch.softmax(
        outputs.logits,
        dim=1
    )

    predicted_class = torch.argmax(
        probabilities,
        dim=1
    ).item()

    confidence = (
        probabilities[0][predicted_class].item() * 100
    )

    return predicted_class, confidence

title = "Government announces new economic policy"

text = """
The government announced a new economic policy
to support economic development and employment.
"""

predicted_class, confidence = predict_news(
    title,
    text
)

print("Predicted class:", predicted_class)
print("Confidence:", round(confidence, 2), "%")

from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)

CORS(
    app,
    resources={
        r"/*": {
            "origins": "*"
        }
    },
    allow_headers=[
        "Content-Type",
        "ngrok-skip-browser-warning"
    ],
    methods=[
        "GET",
        "POST",
        "OPTIONS"
    ]
)

print("Flask API created successfully!")
print(app.url_map)

import threading

def run_flask():
    app.run(
        host="0.0.0.0",
        port=5000,
        debug=False,
        use_reloader=False
    )

flask_thread = threading.Thread(
    target=run_flask
)

flask_thread.start()

print("Flask server started")

import requests

url = "https://cosigner-stunned-sputter.ngrok-free.dev/predict"

data = {
    "title": "Government announces new economic policy",
    "text": "The government announced a new economic policy to support economic development."
}

response = requests.post(
    url,
    json=data
)

print("Status:", response.status_code)
print("Response:", response.json())

!pip install pyngrok

from pyngrok import ngrok

public_url = ngrok.connect(5000)

print("Public URL:", public_url)

import requests

public_url = "https://cosigner-stunned-sputter.ngrok-free.dev"

response = requests.get(public_url)

print("Status:", response.status_code)
print("Response:")
print(response.text)